apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: zcp-system
  labels:
    component: kube-state-metrics 
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    component: kube-state-metrics
