apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- exporters/blackbox-exporter/blackbox-exporter-config-cm.yaml
- exporters/blackbox-exporter/blackbox-exporter-deployment.yaml
- exporters/blackbox-exporter/blackbox-exporter-service.yaml
- exporters/kube-state-metrics/kube-state-metrics-deployment.yaml
- exporters/kube-state-metrics/kube-state-metrics-rbac.yaml
- exporters/kube-state-metrics/kube-state-metrics-svc.yaml
- exporters/node-exporter/node-exporter-ds-svc.yaml
- exporters/node-exporter/node-exporter-ds.yaml
- prometheus/prometheus-cm.yaml
- prometheus/prometheus-deployment.yaml
- prometheus/prometheus-pvc.yaml
- prometheus/prometheus-rbac.yaml
- prometheus/prometheus-rules.yaml
- prometheus/prometheus-service.yaml
- prometheus/prometheus-user-rules.yaml
- prometheus/prometheus-zdb-rules.yaml
- alertmanager/alertmanager-config-cm.yaml
- alertmanager/alertmanager-deployment.yaml
- alertmanager/alertmanager-service.yaml
- alertmanager/alertmanager-template-cm.yaml
- grafana/grafana-cm.yaml
- grafana/grafana-config-provisioning-prometheus.yaml
- grafana/grafana-config-provisioning.yaml
- grafana/grafana-dashboard-addon-cm.yaml
- grafana/grafana-dashboard-cluster-cm.yaml
- grafana/grafana-dashboard-container-cm.yaml
- grafana/grafana-dashboard-system-cm.yaml
- grafana/grafana-deployment.yaml
- grafana/grafana-pvc.yaml
- grafana/grafana-service.yaml
