apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- exporters/node-exporter/node-exporter-ds-svc.yaml
- exporters/node-exporter/node-exporter-ds.yaml
- alertmanager/alertmanager-config-cm.yaml
- alertmanager/alertmanager-deployment.yaml
- alertmanager/alertmanager-service.yaml
- alertmanager/alertmanager-template-cm.yaml
