apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: zcp-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-block-retain-silver"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi