apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: zcp-system
  labels:
    component: blackbox-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    component: blackbox-exporter 
